# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170511_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_job',
            new_name='jobs',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_postcode',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_typeofphone',
            new_name='typeofphone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_age',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default='3', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
