# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170513_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
