# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productinorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='status',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
