# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170519_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
