# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20170602_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
