# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20170602_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalprice_per_product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='totalprice_per_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
