# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20170602_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
