# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20170602_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
